'use client';
import { useEffect, useRef, useState } from 'react';
const directions=['Drag a number into each box, or click a number and then a box. Use all four related facts.','Type the four related multiplication and division facts.','Find the missing number to complete the triangle.'];
type Family={a:number;b:number;hide:number};
function generate(focus:string,old?:Family):Family { let a=6,b=7; do {a=focus==='all'?1+Math.floor(Math.random()*12):Number(focus);b=1+Math.floor(Math.random()*12);}while(old&&a===old.a&&b===old.b);return {a,b,hide:Math.floor(Math.random()*3)}; }
export default function Page(){
 const missingInput=useRef<HTMLInputElement>(null);
 const [page,setPage]=useState(0),[focus,setFocus]=useState('all'),[family,setFamily]=useState<Family>({a:6,b:7,hide:1}),[values,setValues]=useState<string[]>(Array(15).fill('')),[bad,setBad]=useState<number[]>([]),[good,setGood]=useState<number[]>([]),[selected,setSelected]=useState(''),[success,setSuccess]=useState(false),[message,setMessage]=useState(''),[shake,setShake]=useState(0);
 const {a,b}=family,p=a*b,nums=[p,a,b];
 function reset(nextPage=page,nextFocus=focus){setPage(nextPage);setFamily(generate(nextFocus,family));setValues(Array(15).fill(''));setBad([]);setGood([]);setSuccess(false);setMessage('');setSelected('');}
 function put(i:number,v:string){if(success||good.includes(i))return;setValues(x=>x.map((s,j)=>j===i?v:s));setBad(x=>x.filter(j=>j!==i));}
 function check(){const errors:number[]=[],correct:number[]=[];
 if(page===2){const i=12+family.hide;(values[i]!==''&&Number(values[i])===nums[family.hide]?correct:errors).push(i);}
 else {const rows=[values.slice(0,3),values.slice(3,6),values.slice(6,9),values.slice(9,12)];const canonical=[[a,b,p],[b,a,p],[p,a,b],[p,b,a]];const used=new Set<string>();rows.forEach((row,r)=>{const n=row.map(Number),key=n.join(',');const valid=row.every(s=>s!=='')&&canonical.slice(r<2?0:2,r<2?2:4).some(c=>c.every((v,i)=>v===n[i]))&&(!used.has(key)||a===b);if(valid){used.add(key);correct.push(r*3,r*3+1,r*3+2);}else errors.push(r*3,r*3+1,r*3+2);});}
 setBad(errors);setGood(correct);if(errors.length){setShake(x=>x+1);setMessage(page===2?'Check the striped box.':'Check the striped boxes. Each row needs a different related fact.');}else {setSuccess(true);setMessage('');}}
 function field(i:number){return page===0?<button aria-label={`Fact ${Math.floor(i/3)+1}, number ${i%3+1}`} className={`entry ${bad.includes(i)?'incorrect':''} ${good.includes(i)?'right':''}`} onClick={()=>put(i,selected)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();put(i,e.dataTransfer.getData('text/plain'));}} disabled={success||good.includes(i)}>{values[i]||'\u00a0'}</button>:<input ref={page===2?missingInput:undefined} aria-label={i>=12?['Product','Left factor','Right factor'][i-12]:`Fact ${Math.floor(i/3)+1}, number ${i%3+1}`} className={`entry ${bad.includes(i)?'incorrect':''} ${good.includes(i)?'right':''}`} inputMode="numeric" autoComplete="off" value={values[i]} disabled={success||good.includes(i)} onChange={e=>put(i,e.target.value.replace(/[^0-9]/g,''))} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();e.stopPropagation();if(success)reset();else {const inputs=Array.from(document.querySelectorAll<HTMLInputElement>('input:not(:disabled)'));const next=inputs[inputs.indexOf(e.currentTarget)+1];if(next)next.focus();else check();}}}}/>;}
 useEffect(()=>{if(page===2&&!success)missingInput.current?.focus();},[page,family,shake,success]);
 useEffect(()=>{const advance=(e:KeyboardEvent)=>{if(e.key==='Enter'&&success){e.preventDefault();reset();}};document.addEventListener('keydown',advance);return ()=>document.removeEventListener('keydown',advance);});
 return <div className={`page ${success?'successful':''}`}><main className="app-shell"><header className="app-header"><div className="title-group"><h1>Fact Families</h1><p>{directions[page]}</p></div><nav className="nav-pill" aria-label="Activity pages"><button aria-label="Previous page" disabled={page===0} onClick={()=>reset(page-1)}>‹</button><span>{page+1} / 3</span><button aria-label="Next page" disabled={page===2} onClick={()=>reset(page+1)}>›</button></nav></header><section className={`workspace ${bad.length?'workspace-incorrect':''}`} key={shake}><div className="toolbar"><div className="controls"><label>Practice my <select value={focus} onChange={e=>{setFocus(e.target.value);reset(page,e.target.value);}}><option value="all">All facts</option>{Array.from({length:12},(_,i)=><option key={i} value={i+1}>{i+1}s</option>)}</select></label><button className="secondary" onClick={()=>reset()}>New Family</button></div></div><div className="activity"><div className="triangle-panel"><div className="triangle"><svg viewBox="0 0 400 340" aria-hidden="true"><path d="M200 55 L65 280 L335 280 Z" fill="#f1f6ff" stroke="#b8cdee" strokeWidth="4"/></svg><span className="triangle-operations" aria-label="Multiplication and division">×, ÷</span>{nums.map((n,i)=><div key={i} className={`node node-${i}`}>{page===2&&family.hide===i?field(12+i):<button draggable={page===0} className={`number ${selected===String(n)?'selected':''}`} onDragStart={e=>e.dataTransfer.setData('text/plain',String(n))} onClick={()=>setSelected(String(n))} aria-label={`${i===0?'Product':'Factor'} ${n}`}>{n}</button>}</div>)}</div>{a===b&&page<2&&<p className="hint">The factors match, so each pair of facts will match too.</p>}</div><div className="fact-panel">{page<2?<><div className="equations">{[0,1,2,3].map(r=><div className="equation" key={r}>{field(r*3)}<span>{r<2?'×':'÷'}</span>{field(r*3+1)}<span>=</span>{field(r*3+2)}{good.includes(r*3)&&<span className="tick">✓</span>}</div>)}</div></>:<div className="prompt"><h3>What number completes the family?</h3><p>Use the numbers you know to find the missing number.</p></div>}<div className="actions"><button className="primary" onClick={()=>success?reset():check()}>{success?'Correct – Next Family':page===2?'Check Missing Number':'Check'}</button><p className={`feedback ${success?'correct':''}`} role="status">{message||'\u00a0'}</p></div></div></div></section></main></div>;
}
